services:
  backend:
    build:
      context: ./backend
    image: simpleagent-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    image: simpleagent-frontend
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    # Only mount editable source directories to avoid node_modules conflicts
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/postcss.config.js:/app/postcss.config.js
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/.vscode:/app/.vscode:ro
